### ISSUE TITLE
Can't specify schema on tables for redshift

### ISSUE THREAD

**Issue by pedrosmv** [datafold/data-diff#190]
Hello, I'm trying to use the following config file to run the diff between two tables on different schemas on our Redshift cluster but I can't find the proper way to do this. I tried the table with the schema and specifying the schema on the database definition:

This returns `psycopg2.ProgrammingError: invalid dsn: invalid connection option "schema"`
```toml
[database.test_redshift_source]
driver = "redshift"
user = "XXXX"
password = "XXXX"
database = "XXXXX"
host = "XXXXX"
port = 5439
schema="schema_one"

[database.test_redshift_target]
driver = "redshift"
user = "XXXX"
password = "XXXX"
database = "XXXXX"
host = "XXXXX"
port = 5439
schema="schema_two"


[run.default]
update_column = "updated_at"
verbose = true
max_age = "3days"
min_age = "3days"

[run.test_diff]
1.database = "test_redshift_source"
1.table = "table"
2.database = "test_redshift_target"
2.table = "table"
```

This returns `Table 'schema_two.table' does not exist, or has no columns`

```toml
[database.test_redshift_source]
driver = "redshift"
user = "XXXX"
password = "XXXX"
database = "XXXXX"
host = "XXXXX"
port = 5439

[database.test_redshift_target]
driver = "redshift"
user = "XXXX"
password = "XXXX"
database = "XXXXX"
host = "XXXXX"
port = 5439


[run.default]
update_column = "updated_at"
verbose = true
max_age = "3days"
min_age = "3days"

[run.test_diff]
1.database = "test_redshift_source"
1.table = "schema_one.table"
2.database = "test_redshift_target"
2.table = "schema_two.table"

```

I tried looking at the docs, the code and the Python API reference but I couldn't figure out how to make it work :(
