### ISSUE TITLE
Support for database proxy with SSL for Redshift

### ISSUE THREAD

**Issue by johnson-jay-l** [datafold/data-diff#240]
We use a database auth/proxy service for connections to Redshift, and the ssl certificate paths have to be passed into the connect URI.  Here's a working example I use with some of our other db tools (redacted):

`redshift://dbuser@proxy.example.com:443/dbname?sslrootcert=/usr/local/.tsh/keys/proxy.example.com/cas/proxy.example.com.pem&sslcert=/usr/local/.tsh/keys/proxy.example.com/first.last@example.com-db/proxy.example.com/data-warehouse-env-x509.pem&sslkey=/usr/local/.tsh/keys/proxy.example.com/first.last@example.com&sslmode=verify-full`

I tried that syntax with the data-diff CLI and it returned an error:
```
data-diff "redshift://dbuser@proxy.example.com:443/dbname?sslrootcert=/usr/local/.tsh/keys/proxy.example.com/cas/proxy.example.com.pem&sslcert=/usr/local/.tsh/keys/proxy.example.com/first.last@example.com-db/proxy.example.com/data-warehouse-env-x509.pem&sslkey=/usr/local/.tsh/keys/proxy.example.com/first.last@example.com&sslmode=verify-full" content_tags "redshift://dbuser@proxy.example.com:443/dbname?sslrootcert=/usr/local/.tsh/keys/proxy.example.com/cas/proxy.example.com.pem&sslcert=/usr/local/.tsh/keys/proxy.example.com/first.last@example.com-db/proxy.example.com/data-warehouse-env-x509.pem&sslkey=/usr/local/.tsh/keys/proxy.example.com/first.last@example.com&sslmode=verify-full" content_tags_v2
```

It returns:

```ERROR - Too many parts to path. Expected format: redshift://<user>:<pass>@<host>/<database>```

Note that without enclosing the db URI in double quotes, it returns ```zsh: parse error near `&'```

Is there another way to connect to Redshift using SSL certs, and/or a syntax we can use to pass in arbitrary URI arguments either from the CLI or from a TOML config?

Thanks!

**Comment by erezsh** [comment]
P.S. Just to get you started, here's how Presto + cert might look like in a config file:

```toml
[database.presto]
driver = "presto"
host = "<presto hostname>"
port = "<presto port>"
user = "<presto user>"
password = "<presto password>"
catalog = "<presto catalog>"
schema = "<presto schema>"
cert = "path/to/presto/certificate.cer"
auth = "basic"
http_scheme = "https"
source = "odbc"
```
