### ISSUE TITLE
Database environments should always have custom_schemas: False

### ISSUE THREAD

**Issue by dlawin** [datafold/data-diff#453]
**Describe the bug**
There is no scenario where this configuration should be used:
```
vars:
  data_diff:
    prod_database: prod_db
    custom_schemas: True
```

Since `True` is the assumed value of custom_schemas, this is super confusing at the moment. As you will always want
```
vars:
  data_diff:
    prod_database: prod_db
    custom_schemas: False
```
and not
```
vars:
  data_diff:
    prod_database: prod_db
```

when using database environments. The value of custom_schemas should always be false when only a database is provided. Consider throwing a warning and/or ignoring this setting when `prod_database is not None and prod_schema is None`

Doc should be updated to only highlight this option when using schema environments.
