### ISSUE TITLE
unused target env_vars causing "Env var required but not provided"

### ISSUE THREAD

**Issue by dlawin** [datafold/data-diff#626]
**Describe the bug**
I am trying to run data-diff but seeing this error:
```
Running with data-diff=0.7.10
[18:45:44] ERROR - Parsing Error
  Env var required but not provided: 'some_env_var'
```

Even though my profile's target does not contain an env_var. 

This is being caused by unused targets within the profile. e.g. `dev_other_not_used` in the example below:
```
snowflake:
  outputs:
    dev:
      account: an_account
      database: a_database
      password: a_password
      role: a_role
      schema: a_schema
      type: snowflake
      user: a_user
      warehouse: a_warehouse
    dev_other_not_used:
      account: an_account
      database: a_database
      password: "{{ env_var('some_env_var') }}" # this causes error although it is not used
      role: a_role
      schema: a_schema
      type: snowflake
      user: a_user
      warehouse: a_warehouse
  target: dev
```
