### ISSUE TITLE
Add support for [motherduck](https://motherduck.com/)

### ISSUE THREAD

**Issue by sungchun12** [datafold/data-diff#657]
Problem: I want to use Motherduck (serverless duckdb) to run my data diffs. However, whenever I try to run it, the default duckdb adapter doesn't recognize the new syntax.

```yaml
jaffle_shop:

  target: dev
  outputs:
    dev:
      type: duckdb
      schema: dev_sung # update this for your own schema
      path: 'jaffle_shop.duckdb'
      threads: 16

    prod:
      type: duckdb
      schema: prod_sung # update this for your own schema
      path: 'md:jaffle_shop' # data-diff says this is a syntax error
      threads: 16
```

Solution: Make data-diff recognize Motherduck duckdb databases.

Reference project with demo video: https://github.com/sungchun12/jaffle_shop_duckdb

[Authenticating to Motherduck](https://motherduck.com/docs/authenticating-to-motherduck#using-the-service-token-to-connect)
