### ISSUE TITLE
concat pks not being detected

### ISSUE THREAD

**Issue by dlawin** [datafold/data-diff#663]
**Describe the bug**
```
models:
- name: [..]
  description: [...] 
  Columns:
[...]
  tests:
    - unique:
        column_name: "id || another_id"
```

User reports these types of tests are not being detected as keys and they see this message:
`Skipped due to unknown primary key. Add uniqueness tests, meta, or tags.`

Likely a bug in this method: https://github.com/datafold/data-diff/blob/f80dc586b4a4f4844ae99cf0d2c93b831aa33890/data_diff/dbt_parser.py#L428
